# User config
author: "dongcheolpark"
tagline: "Pineapple Certfied Jekyll Theme"
description: "I have interested in dotnet, algorithm and data structure"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "head02325@soongsil.ac.kr"
velog : "https://velog.io/@head022"
instagram : "https://www.instagram.com/dongcheol022/"
github: "https://github.com/dongcheolpark"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
